version: "3"
services:
  php_apache:
    container_name: php_8.2_apache_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:80
    networks:
      - projekt_share_network
    depends_on:
      - mysql
    volumes:
      - .:/var/www/html

  mysql:
    image: mysql:8.1.0
    container_name: mysql_8.1.0_container
    environment:
      MYSQL_ROOT_PASSWORD: Qwerty12345
      MYSQL_DATABASE: notes2
      MYSQL_USER: root
    ports:
      - "3306:3306"
    volumes:
      - C:\projekt_share\mysql:/var/lib/mysql  
    networks:
      - projekt_share_network 

  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: phpmyadmin_container
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    networks:
      - projekt_share_network        

networks:
  projekt_share_network: